### ISSUE TITLE
mysql 8 -no ingresa

### ISSUE THREAD

**Issue by edisaac** [jrichardsz/oauth2-shield#14]
docker run --name mysqldb2 -p 3306:3306 -e MYSQL_USER=mysql -e MYSQL_PASSWORD=mysql -e MYSQL_DATABASE=bd_integracion -e MYSQL_ROOT_PASSWORD=supersecret -d mysql:8.0.17

al usar esa base de datos version 8 sale error

error when connecting to db: Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Handshake.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Handshake.js:103:18)
    at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:103:28)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    --------------------
    at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/app/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/app/node_modules/mysql/lib/Connection.js:130:18)
    at Timeout.handleDisconnect [as _onTimeout] (/app/database/DatabaseConnection.js:65:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  code: 'ER_NOT_SUPPORTED_AUTH_MODE',
  errno: 1251,
  sqlMessage: 'Client does not support authentication protocol requested by server; consider upgrading MySQL client',
  sqlState: '08004',
  fatal: true
}
select * from credential where application

**Comment by jrichardsz** [comment]
I will review this issue.
until I finish it, I will add the 5.7 mysql version as requirement!
Thanks
